delete from Pizza_Order_Pizzas;
delete from Pizza_Ingredients;
delete from Pizza;
delete from Pizza_Order;
delete from Ingredient;

insert into Ingredient (id, name, type) values ('PSZY', 'szynka', 'PROTEIN');
insert into Ingredient (id, name, type) values ('PBCZ', 'boczek wędzony', 'PROTEIN');
insert into Ingredient (id, name, type) values ('PKUR', 'kurczak', 'PROTEIN');
insert into Ingredient (id, name, type) values ('PSAL', 'salami', 'PROTEIN');
insert into Ingredient (id, name, type) values ('PKIE', 'kiełbasa', 'PROTEIN');
insert into Ingredient (id, name, type) values ('VPOM', 'pomidor', 'VEGETABLE');
insert into Ingredient (id, name, type) values ('VPAP', 'papryka', 'VEGETABLE');
insert into Ingredient (id, name, type) values ('VRUK', 'rukola', 'VEGETABLE');
insert into Ingredient (id, name, type) values ('VKUK', 'kukurydza', 'VEGETABLE');
insert into Ingredient (id, name, type) values ('VPIP', 'pikantna papryczka', 'VEGETABLE');
insert into Ingredient (id, name, type) values ('FLOS', 'łosoś', 'FISH');
insert into Ingredient (id, name, type) values ('FTUN', 'tuńczyk', 'FISH');
insert into Ingredient (id, name, type) values ('FANA', 'ananas', 'FRUIT');
insert into Ingredient (id, name, type) values ('FGRU', 'gruszka', 'FRUIT');
insert into Ingredient (id, name, type) values ('CMOZ', 'mozarella', 'CHEESE');
insert into Ingredient (id, name, type) values ('CCHE', 'cheddar', 'CHEESE');
insert into Ingredient (id, name, type) values ('SKET', 'ketchup', 'SAUCE');
insert into Ingredient (id, name, type) values ('SCZS', 'sos czosnkowy', 'SAUCE');